#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

config_path=$(ynh_app_setting_get --app=$app --key=config_path)

#=================================================
# REMOVE Keycloak
#=================================================
ynh_script_progression --message="Removing Keycloak"

pushd $config_path

docker-compose --log-level CRITICAL down

popd 

#=================================================
# REMOVE APP CONFIG DIR
#=================================================
ynh_script_progression --message="Removing app directory"

ynh_secure_remove --file="$config_path"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
