#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

config_path=$(ynh_app_setting_get --app=$app --key=config_path)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status $app >/dev/null 2>&1
then
	ynh_script_progression --message="Removing $app service"
	yunohost service remove $app
fi

#=================================================
# REMOVE Keycloak
#=================================================
ynh_script_progression --message="Removing Keycloak"

pushd $config_path

docker-compose down

popd 

#=================================================
# REMOVE APP CONFIG DIR
#=================================================
ynh_script_progression --message="Removing app directory"

ynh_secure_remove --file="$config_path"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
